Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.name = "k8s-eckAction-node1-48"
    v.memory = 8192
    v.cpus = 2
  end

  config.vm.define :node do |node|
    node.vm.box = "ubuntu/xenial64"
    node.vm.box_url = "https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"
    node.vm.hostname = "eckAction-node1-48"
    node.vm.network "public_network"
    node.vm.synced_folder "./sync_dir", "/vagrant_sync_dir"
    node.vm.provision "shell", inline: $kubeadm_install
  end

end

$kubeadm_install = <<-SCRIPT
# add gpg key file
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

# add kubernetes source to deb db
cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF

# install kubeadm, kubelet, kubectl, kubernetes-cni
apt-get update
apt-get install -y docker.io kubeadm

# join to master
sudo kubeadm join 192.168.0.210:6443 --token qpdh2q.pjb69c8etdbkxtrx --discovery-token-ca-cert-hash sha256:3e5788f4f17f782e53c939bf7817d884b711acb55481eeac2438cb9d1a6f7257

# deploy network plugin
# sudo kubectl apply -f "https://frontend.dev.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

SCRIPT
