Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.name = "k8s-eckAction-node1-48"
    v.memory = 8192
    v.cpus = 2
  end

  config.vm.define :node do |node|
    node.vm.box = "ubuntu/xenial64"
    node.vm.box_url = "https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"
    node.vm.hostname = "eckAction-node1-48"
    node.vm.network "public_network"
    node.vm.synced_folder "./sync_dir", "/vagrant_sync_dir"
    node.vm.provision "shell", inline: $kubeadm_install
  end

end

$kubeadm_install = <<-SCRIPT
# add gpg key file
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

# add kubernetes source to deb db
cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF

# install kubeadm, kubelet, kubectl, kubernetes-cni
apt-get update
apt-get install -y docker.io kubeadm

# join to master
sudo kubeadm join 10.0.2.15:6443 --token a6a2bw.8bilxcpgh8qcmm5u --discovery-token-ca-cert-hash sha256:7a959216821f638eea139dec84505814b95f93f167a76527932730400d77cf10

SCRIPT
